# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7c1c7d03b771d40ede7de76e14610efc4a8976e7dfe19d49292fd8230880f78d2d0bb76875c372e8853579624540bc8e60c7a609132d2afe938524d540eb98

test:
  secret_key_base: b620f9ceb91e38b6f550ac53be580ffdd7ad1a732139fe72f0ee026d6c06345e21f24cb898b7fca0f309c05e9fbd38bcaebf9b3892071371ec60064c96236c27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
